# clase comentareada

spring.application.name=artcook
spring.datasource.url=jdbc:mysql://5.tcp.ngrok.io:29865/base55
spring.datasource.username=estudiantedes3
spring.datasource.password=desarrollo2026$
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
server.port=8081

# Correo gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=artcook.verify@gmail.com
spring.mail.password=gziw zshu pnnm sxyv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# URL base del backend para los links del correo de verificacion
app.base-url=http://localhost:4200

# APIs de IA
app.openai.api-key=pending
app.gemini.api-key=AIzaSyC3Hn4OquMkWasPqTZi9qWxFuWt0knTJfo
app.claude.api-key=pending
