spring.application.name=artcook
spring.datasource.url=jdbc:mysql://5.tcp.ngrok.io:29865/base55
spring.datasource.username=estudiantedes3
spring.datasource.password=desarrollo2026$
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
server.port=8081

# Correo gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=artcook.verify@gmail.com
spring.mail.password=gziw zshu pnnm sxyv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Usuario y contrasena
admin.email=admin@artcook.com
admin.password=Admin123!
user.email=usuario@artcook.com
user.password=User123!

# URL base del backend para los links del correo de verificacion
app.base-url=http://localhost:4200

# APIs de IA
app.openai.api-key=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
app.gemini.api-key=AIzaSyAQMtHj2iXEukoZnQvlIQkVbBUS2OnYcD0
app.claude.api-key=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


# JWT - clave secreta para firmar los tokens (minimo 32 caracteres)
jwt.secret=artcookSecretKeyParaJWTQueDebeSerLarga2026

# JPA - mostrar SQL en consola (util para desarrollo)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Deshabilitar open-in-view para evitar warnings
spring.jpa.open-in-view=false

# Configuracion de subida de archivos (para PDFs y videos)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# APIs Generacion de videos
app.falai.api-key=c0c2156d-a95a-4218-90e9-1a3cb36a860f:1edec5f96b5ff0f90a6a557a376a124e
deepgram.api.key=16e459867e0898111b8b5d5bf3cd535d8ea216e7
app.videos.path=videos
app.ffmpeg.path=C:/Users/deiby/ffmpeg/bin/ffmpeg.exe